# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'szsurge_ui0.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1520, 879)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 0, 801, 61))
        self.label.setStyleSheet("font: 75 26pt \"微软雅黑\";")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 331, 121))
        self.groupBox.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 20, 251, 71))
        self.groupBox_5.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 43, 31, 20))
        self.lineEdit_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_9.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(50, 43, 31, 20))
        self.lineEdit_10.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_11.setGeometry(QtCore.QRect(90, 43, 31, 20))
        self.lineEdit_11.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_12.setGeometry(QtCore.QRect(130, 43, 31, 20))
        self.lineEdit_12.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(170, 43, 31, 20))
        self.lineEdit_13.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(210, 43, 31, 20))
        self.lineEdit_14.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.label_16.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(50, 20, 31, 21))
        self.label_17.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(90, 20, 31, 21))
        self.label_18.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(130, 20, 31, 21))
        self.label_19.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(170, 20, 31, 21))
        self.label_20.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(220, 20, 16, 21))
        self.label_21.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_21.setObjectName("label_21")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 80, 61, 31))
        self.pushButton_2.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(100, 95, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 50, 61, 21))
        self.pushButton_3.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 20, 61, 21))
        self.pushButton_4.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 95, 81, 21))
        self.label_22.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_22.setObjectName("label_22")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_15.setGeometry(QtCore.QRect(210, 94, 41, 20))
        self.lineEdit_15.setText("")
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(170, 94, 41, 21))
        self.label_23.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_23.setObjectName("label_23")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 70, 171, 121))
        self.groupBox_2.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 40, 31, 20))
        self.lineEdit_3.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 40, 31, 20))
        self.lineEdit_4.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 80, 31, 20))
        self.lineEdit_5.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 80, 31, 20))
        self.lineEdit_6.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.label_5.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(90, 40, 21, 21))
        self.label_6.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 21, 21))
        self.label_7.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(90, 80, 21, 21))
        self.label_8.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(70, 40, 16, 21))
        self.label_11.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(150, 40, 16, 21))
        self.label_12.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(70, 80, 16, 21))
        self.label_13.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(150, 80, 16, 21))
        self.label_14.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_14.setObjectName("label_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 70, 161, 121))
        self.groupBox_3.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 80, 61, 21))
        self.comboBox_2.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(90, 30, 61, 31))
        self.pushButton.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 53, 31, 20))
        self.lineEdit_7.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 80, 31, 20))
        self.lineEdit_8.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 27, 51, 21))
        self.label_15.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_15.setObjectName("label_15")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(50, 53, 21, 21))
        self.label_24.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(50, 80, 21, 21))
        self.label_25.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.label_25.setObjectName("label_25")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(850, 80, 650, 370))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(10, 40, 631, 320))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 251, 21))
        self.label_2.setStyleSheet("font: 75 14pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(850, 470, 650, 370))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 40, 630, 320))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(220, 10, 251, 21))
        self.label_3.setStyleSheet("font: 75 14pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 200, 830, 630))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 811, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.tabWidget.setStyleSheet("QTabBar::tab{height:32;width:200;font: 75 12pt \"微软雅黑\";};\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_5.setGeometry(QtCore.QRect(10, 40, 791, 541))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(300, 10, 181, 21))
        self.label_28.setStyleSheet("font: 75 14pt \"微软雅黑\";")
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 40, 791, 541))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(330, 10, 181, 21))
        self.label_27.setStyleSheet("font: 75 14pt \"微软雅黑\";")
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(0, 40, 801, 541))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_5.setGeometry(QtCore.QRect(22, 13, 95, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(599, 10, 95, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(700, 10, 95, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(280, 10, 191, 21))
        self.label_26.setStyleSheet("font: 75 14pt \"微软雅黑\";")
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab_2, "")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(700, 80, 141, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 71, 21))
        self.label_4.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_9.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.label_10.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_10.setObjectName("label_10")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 50, 66, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_4.setGeometry(QtCore.QRect(70, 80, 66, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1520, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "深圳市基于GPU加速的台风风暴潮集合预报系统"))
        self.groupBox.setTitle(_translate("MainWindow", "输入 && 启动"))
        self.groupBox_5.setTitle(_translate("MainWindow", "误差半径及大风半径增减（km）"))
        self.lineEdit_9.setText(_translate("MainWindow", "60"))
        self.lineEdit_10.setText(_translate("MainWindow", "100"))
        self.lineEdit_11.setText(_translate("MainWindow", "120"))
        self.lineEdit_12.setText(_translate("MainWindow", "150"))
        self.lineEdit_13.setText(_translate("MainWindow", "180"))
        self.lineEdit_14.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "24h"))
        self.label_17.setText(_translate("MainWindow", "48h"))
        self.label_18.setText(_translate("MainWindow", "72h"))
        self.label_19.setText(_translate("MainWindow", "96h"))
        self.label_20.setText(_translate("MainWindow", "120h"))
        self.label_21.setText(_translate("MainWindow", "dR"))
        self.pushButton_2.setText(_translate("MainWindow", "启动"))
        self.comboBox.setItemText(0, _translate("MainWindow", "145个"))
        self.comboBox.setItemText(1, _translate("MainWindow", "125个"))
        self.comboBox.setItemText(2, _translate("MainWindow", "105个"))
        self.comboBox.setItemText(3, _translate("MainWindow", "85个"))
        self.comboBox.setItemText(4, _translate("MainWindow", "65个"))
        self.comboBox.setItemText(5, _translate("MainWindow", "45个"))
        self.comboBox.setItemText(6, _translate("MainWindow", "25个"))
        self.pushButton_3.setText(_translate("MainWindow", "采集"))
        self.pushButton_4.setText(_translate("MainWindow", "读取"))
        self.label_22.setText(_translate("MainWindow", "集合成员设定"))
        self.label_23.setText(_translate("MainWindow", "TY ID"))
        self.groupBox_2.setTitle(_translate("MainWindow", "画图区域设定"))
        self.lineEdit_3.setText(_translate("MainWindow", "110"))
        self.lineEdit_4.setText(_translate("MainWindow", "118"))
        self.lineEdit_5.setText(_translate("MainWindow", "19"))
        self.lineEdit_6.setText(_translate("MainWindow", "24"))
        self.label_5.setText(_translate("MainWindow", "西"))
        self.label_6.setText(_translate("MainWindow", "东"))
        self.label_7.setText(_translate("MainWindow", "南"))
        self.label_8.setText(_translate("MainWindow", "北"))
        self.label_11.setText(_translate("MainWindow", "E"))
        self.label_12.setText(_translate("MainWindow", "E"))
        self.label_13.setText(_translate("MainWindow", "N"))
        self.label_14.setText(_translate("MainWindow", "N"))
        self.groupBox_3.setTitle(_translate("MainWindow", "产品制作"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "惠州"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "盐田"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "大梅沙"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "深圳东山"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "深圳机场"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "深圳南澳"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "赤湾"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "前海湾"))
        self.pushButton.setText(_translate("MainWindow", "画图"))
        self.lineEdit_7.setText(_translate("MainWindow", "0"))
        self.lineEdit_8.setText(_translate("MainWindow", "默认"))
        self.label_15.setText(_translate("MainWindow", "色标范围"))
        self.label_24.setText(_translate("MainWindow", "cm"))
        self.label_25.setText(_translate("MainWindow", "cm"))
        self.label_2.setText(_translate("MainWindow", "风暴增水过程曲线图"))
        self.label_3.setText(_translate("MainWindow", "总潮位过程曲线图"))
        self.label_28.setText(_translate("MainWindow", "台风集合预报成员图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "台风集合预报成员图"))
        self.label_27.setText(_translate("MainWindow", "最大风暴增水分布图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "最大风暴增水分布图"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", ">0.5米概率"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", ">1.0米概率"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", ">1.5米概率"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", ">2.0米概率"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", ">2.5米概率"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", ">3.0米概率"))
        self.pushButton_5.setText(_translate("MainWindow", "上一张"))
        self.pushButton_6.setText(_translate("MainWindow", "下一张"))
        self.label_26.setText(_translate("MainWindow", "风暴潮增水概率分布图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "风暴增水概率分布图"))
        self.label_4.setText(_translate("MainWindow", "案例查询"))
        self.label_9.setText(_translate("MainWindow", "台风编号"))
        self.label_10.setText(_translate("MainWindow", "操作时间"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "2018"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2017"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "103014"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "103015"))
