DEFAULT_FK = -1
ABS_KEY = -1  # 配合抽象类使用的 ABS_KEY
DEFAULT_NULL_KEY = -1
DEFAULT_NULL_VAL = 'NULL'
DEFAULT_CODE = 'DEFAULT'
UNLESS_INDEX = -1
DEFAULT_STEP = 5
UNLESS_ID = -999
UNLESS_CELERY_ID = 'NULL'

# typhoon
UNLESS_TY_CODE = 'DEFAULT'

# 默认未赋值的默认时间戳字符串
DEFAULT_TIMTSTAMP_STR = '000000'

# 默认的概率
DEFAULT_PRO = 0.5
